# Generated by Django 4.2.1 on 2023-05-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Miz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ResType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReternType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('values', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tafahom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('createDate', models.CharField(max_length=10)),
                ('expirDate', models.CharField(max_length=10)),
                ('loanRow', models.CharField(max_length=10)),
                ('des', models.TextField()),
                ('hesab', models.CharField(max_length=50)),
                ('code_kanun', models.BigIntegerField(help_text=' کد کانون')),
                ('mablagh_limit', models.DecimalField(decimal_places=0, help_text='سقف مبلغ', max_digits=18)),
                ('modat_limit', models.IntegerField(help_text='سقف مدت')),
                ('person_limit', models.IntegerField(help_text='سقف نفر')),
                ('is_blocked', models.BooleanField(default=False, help_text='اگر حساب مسدود باشد True می شود', verbose_name='Hesab is blocked?')),
                ('is_bime', models.BooleanField(default=False, help_text='اگر وام بیمه باشد True می شود', verbose_name='Vaam is bime?')),
                ('by_sign', models.BooleanField(default=False, help_text='اگر وام برای امضا ارسال شود  True می شود', verbose_name='Vaam by sign?')),
                ('law_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.law')),
                ('miz_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.miz')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.organization')),
                ('retern_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.reterntype')),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_num', models.CharField(max_length=50)),
                ('mail_date', models.CharField(max_length=10)),
                ('action_date', models.CharField(max_length=10)),
                ('code_meli', models.CharField(max_length=11)),
                ('mablagh', models.DecimalField(decimal_places=0, help_text='مبلغ', max_digits=12)),
                ('modat', models.IntegerField(help_text='مدت')),
                ('res_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.restype')),
                ('tafahom_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.tafahom')),
            ],
        ),
        migrations.AddField(
            model_name='tafahom',
            name='verifier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.verifier'),
        ),
        migrations.CreateModel(
            name='ResPerTafahom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.DecimalField(decimal_places=0, help_text='مبلغ', max_digits=18)),
                ('res_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.restype')),
                ('tafahom_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tafahom.tafahom')),
            ],
        ),
    ]
