# Generated by Django 4.1.9 on 2023-05-18 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tafahom", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Setting",
        ),
        migrations.AlterModelOptions(
            name="restype",
            options={
                "verbose_name": "نوع منبع وام",
                "verbose_name_plural": "نوع منابع وام",
            },
        ),
    ]
