# Generated by Django 4.1.9 on 2023-05-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tafahom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="values",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="مقدار"
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="code_kanun",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="کد کانون"
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="des",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="expirDate",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ ابطال"),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="hesab",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="حساب"
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="law_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.law",
                verbose_name="قانون",
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="loanRow",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ردیف وام"
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="mablagh_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=18,
                null=True,
                verbose_name="سقف مبلغ وام",
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="miz_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.miz",
                verbose_name="میز کار",
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="modat_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="سقف مدت وام"
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="organization_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.organization",
                verbose_name=" سازمان",
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="person_limit",
            field=models.IntegerField(blank=True, null=True, verbose_name="سقف نفرات"),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="retern_type_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.reterntype",
                verbose_name="نحوه باز پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="tafahom",
            name="verifier_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.verifier",
                verbose_name="تائید کننده",
            ),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="action_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="code_meli",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="mail_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ نامه"),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="mail_num",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="شماره نامه"
            ),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="modat",
            field=models.IntegerField(
                blank=True, help_text="مدت", null=True, verbose_name="مدت"
            ),
        ),
        migrations.AlterField(
            model_name="vaam",
            name="res_type_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tafahom.restype",
                verbose_name="نوع منبع",
            ),
        ),
    ]
