# Generated by Django 4.1.9 on 2023-05-18 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tafahom", "0002_delete_setting_alter_restype_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="respertafahom",
            unique_together={("tafahom_id", "res_type_id")},
        ),
    ]
