# Generated by Django 4.1.9 on 2023-05-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tafahom", "0003_alter_respertafahom_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaam",
            name="des",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="vaam",
            name="is_duplicate",
            field=models.BooleanField(default=False, verbose_name="تکراری؟"),
        ),
        migrations.AddField(
            model_name="vaam",
            name="is_variz",
            field=models.BooleanField(default=False, verbose_name="واریز شده؟"),
        ),
    ]
